version: '3.7'

services:
  db2:
    container_name: db2
    image: mariadb:10.11
    labels:
      - pma.allow_config=true
      - pma.cfg.verbose=app2_db
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
    networks:
      - net

networks:
  net:
    name: phpmyadmin_net
    external: true
